// NOTE: keep this file ASCII-only.
// Emission, gated by a KEYWORD.
// Two hard-won facts decide this shape:
//  1. Shader Core does not deliver module floats/colours/textures to the shader here, so the only
//     per-material switches that work are keywords (SCConstValue -> '#define NAME 1').
//  2. The shared mask is a [SCMask] texture generated by Shader Core from a .scmask asset. A material
//     WITHOUT that asset samples the white default, so an ungated '+= sd.mask.rgb' adds about +2 to
//     every pixel and blows the avatar out (measured: pure NonToon 0.414 vs ungated 0.908).
// So the addition runs only when the converter turned the keyword on.
if (_Enable)
{
    #if _EmissionOn == 1
        half3 emission = half3(sd.mask.r, sd.mask.g, sd.mask.b);
        sd.lightColor += emission / max(sd.albedoAlpha.rgb, 0.5h);
    #endif
}
