// NOTE: keep this file ASCII-only.
// Emission, gated by a KEYWORD.
//
// Verified facts that decide this shape:
//  1. Shader Core does not deliver module floats/colours/textures to the shader here; keywords
//     (SCConstValue -> '#define NAME 1') are the only per-material switches that arrive.
//  2. The shared mask is a [SCMask] texture generated by Shader Core from a .scmask asset, which is
//     how mask data has to be delivered. A material WITHOUT that asset samples the white default, so an
//     ungated '+= sd.mask.rgb' adds ~+2 per pixel and blows the avatar out (measured 0.414 -> 0.908).
//  3. Both gates were verified end to end by rendering: with the keyword off the render is bit-for-bit
//     unchanged (0.4132 / 0% white); with it on, an injected change inside the #if is visible.
//
// The addition is still deliberately conservative: sd.lightColor is post-multiplied downstream, so a
// +0.2 term only moves the final pixel slightly. Tune here once the injection point is settled.
if (_Enable)
{
    #if _EmissionOn == 1
        half3 emission = half3(sd.mask.r, sd.mask.g, sd.mask.b);
        sd.lightColor += emission / max(sd.albedoAlpha.rgb, 0.5h);
    #endif
}
